name: Fetch Latest Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '2-59/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            get_image.py
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        id: fetch_image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python get_image.py

      - name: Report status
        run: |
          echo "New image: ${{ steps.fetch_image.outputs.new_image_path }}"
          echo "Skipped image: ${{ steps.fetch_image.outputs.skipped_image_path }}"
          echo "Latest image: ${{ steps.fetch_image.outputs.latest_image_path }}"
          echo "Status: ${{ steps.fetch_image.outputs.status }}"
